# Generated by Django 6.0.3 on 2026-03-10 15:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Code unique auto-généré (ex: VNT-2024-0001)', max_length=50, unique=True, verbose_name='Référence')),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de vente')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant total calculé automatiquement', max_digits=10, verbose_name='Total TTC')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('completee', 'Complétée'), ('annulee', 'Annulée')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente'],
                'indexes': [models.Index(fields=['-date_vente'], name='ventes_vent_date_ve_cbfbb0_idx'), models.Index(fields=['statut'], name='ventes_vent_statut_4c1c73_idx'), models.Index(fields=['reference'], name='ventes_vent_referen_1a77bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix au moment de la vente (snapshot)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix unitaire')),
                ('sous_total', models.DecimalField(decimal_places=2, help_text='Calculé: quantité × prix_unitaire', max_digits=10, verbose_name='Sous-total')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ventes', to='medicaments.medicament', verbose_name='Médicament')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.vente', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
                'ordering': ['id'],
            },
        ),
    ]
